### ISSUE TITLE
Clean up base patch build toolchain

### ISSUE THREAD

**Issue by mike8699** [phst-randomizer/ph-randomizer#22]
- `fixy9.exe` is a closed-source windows utility for updating the y9.bin manifest after making changes to overlay files. Since our docker image for running the toolchain is based on debian, running this tiny utility requires downloading and installing Wine, which adds several minutes to the build time.

- CUE's compression tools are a set of C programs for decompressing/compressing various GBA/NDS compression formats. We use it to (de)compress the arm9.bin and overlay executables which are in BLZ format. Unfortunately, the original code is written using some windows-exclusive library functions, so I [forked](https://github.com/phst-randomizer/nds-compressors) it and changed those function calls to more standardized libc calls so we can use it in our Debian-based docker image. Ideally we stop relying on these tools and just delete that repo.

As far as a solution, ndspy has support for extracting/inserting arm9.bin and overlay files from roms, and handles any (de)compression and y9.bin updates automatically. So, I think the best thing to do would be write a Python script that effectively does what the `arm9.bin overlay` Makefile target does, except using [`ndspy`'s code API](https://ndspy.readthedocs.io/en/latest/api/code.html)

**Comment by mikeoss** [comment]
Coming back to this now. More specifically what needs to happen is

- [ ] Replace usage of CUE's BLZ tool with `ndspy_codeCompression` CLI
- [ ] Get rid of [this horrible one-line inline python script](https://github.com/phst-randomizer/ph-randomizer/blob/main/base/Makefile#L60). Hopefully ndspy can replace that + the slicing and dicing of the arm9.bin file with `dd` earlier on in that file.
- [ ] Write a script using the `ndspy.code` API to update the y9.bin manifest with the new overlay information and drop wine as a dependency in the Dockerfile.
