### ISSUE TITLE
Integrate D-Pad patch?

### ISSUE THREAD

**Issue by NQNStudios** [phst-randomizer/ph-randomizer#416]
I wonder, could the D-pad patch described here be integrated as a randomizer quality-of-life option?

https://retrogamecorps.com/2020/09/24/guide-enable-d-pad-controls-on-the-legend-of-zelda-nintendo-ds-games/

I vaguely remember reading somewhere that it already was, but I don't see that in the README, so maybe I'm remembering wrong.

**Comment by mike8699** [comment]
You probably saw this https://github.com/phst-randomizer/ph-randomizer/discussions/246#discussioncomment-4385556.

As we develop the randomizer, we're taking care not to touch any of the memory locations used by the Dpad patch; so, it will definitely be possible for one to run the randomizer on a rom that has the dpad patch applied. Including it in the randomizer as an option is certainly something we will look at in the future once we have a stable release ready.
