### ISSUE TITLE
Proposal to change to MIT license

### ISSUE THREAD

**Issue by mike8699** [phst-randomizer/ph-randomizer#445]
If you approve of the proposal to change the license of this project (https://github.com/phst-randomizer/ph-randomizer/) from GPL v3 to MIT, reply to this issue with the following using the github account you contributed to this repo with:

"I agree to share all of my contributions, both present and prior to the https://github.com/phst-randomizer/ph-randomizer/ repository under MIT."

**Comment by mike8699** [comment]
I agree to share all of my contributions, both present and prior to the https://github.com/phst-randomizer/ph-randomizer/ repository under MIT.

**Comment by lunarsoap5** [comment]
I agree to share all of my contributions, both present and prior to the https://github.com/phst-randomizer/ph-randomizer/ repository under MIT.

**Comment by Redriel57** [comment]
I agree to share all of my contributions, both present and prior to the https://github.com/phst-randomizer/ph-randomizer/ repository under MIT.

**Comment by NoobTenLuka** [comment]
I agree to share all of my contributions, both present and prior to the https://github.com/phst-randomizer/ph-randomizer/ repository under MIT.

**Comment by SammygoodTunes** [comment]
I agree to share all of my contributions, both present and prior to the https://github.com/phst-randomizer/ph-randomizer/ repository under MIT.
